import type { Socket } from "bun";
import type { ChatMode } from "wow/client";
import type { CombatRuntime } from "wow/combat";
import type { ControlRuntime } from "wow/control";
import type { Arc4 } from "wow/crypto/arc4";
import type { EncounterCycleRuntime } from "wow/encounter-cycle";
import type { EntityStore } from "wow/entity-store";
import type { FriendStore } from "wow/friend-store";
import type { GuildStore } from "wow/guild-store";
import type { IgnoreStore } from "wow/ignore-store";
import type { ChatMessage as RawChatMessage } from "wow/protocol/chat";
import type { AccumulatorBuffer, OpcodeDispatch } from "wow/protocol/world";
import type { QuestRuntime } from "wow/quests";
import type { RecoveryRuntime } from "wow/recovery";
import type { RemoteMotion } from "wow/remote-motion";
import type { RewardsRuntime } from "wow/rewards";
import type { TacticsLoop } from "wow/tactics";
import type { WorldEvents } from "wow/world-events";

export type WorldConn = {
  socket?: Socket;
  dispatch: OpcodeDispatch;
  buf: AccumulatorBuffer;
  arc4?: Arc4;
  startTime: number;
  pendingHeader?: { size: number; opcode: number };
  dispatchingOpcode?: number;
  nameCache: Map<number, string>;
  pendingMessages: Map<number, RawChatMessage[]>;
  channels: string[];
  lastChatMode: ChatMode;
  selfName: string;
  selfClass?: string;
  selfGuidLow: number;
  selfGuidHigh: number;
  partyMembers: Map<string, { guidLow: number; guidHigh: number }>;
  entityStore: EntityStore;
  remoteMotion: RemoteMotion;
  creatureNameCache: Map<number, string>;
  gameObjectNameCache: Map<number, string>;
  pendingNameQueries: Set<string>;
  friendStore: FriendStore;
  ignoreStore: IgnoreStore;
  guildStore: GuildStore;
  guildId: number;
  pendingRequest: "group" | "duel" | null;
  duelArbiter: bigint;
  events: WorldEvents;
  control?: ControlRuntime;
  combat?: CombatRuntime;
  recovery?: RecoveryRuntime;
  quests?: QuestRuntime;
  rewards?: RewardsRuntime;
  cycle?: EncounterCycleRuntime;
  tactics?: TacticsLoop;
};
